#+title: notes for scripts
#+author: Bin He

* <2019-02-17 Sun> assemble Carl's sequence, generalize the script
To make the script applicable for similar analysis, I generalized it a bit by putting the input and output file names as the first two lines of the strain names file. This allows me to use the same script, with parameters in a separate file. The new script is called assembl-seq-2019-02-16.sh
** TODO Take raw sequences and strandedness as input 
this script still has the post-fixes of the sequence names fixed. Ideally, the script should be able to work on any arbitrary post-fixes, whose values and strandedness can be supplied either at the command line or as part of the input file.
* <2018-10-07 Sun> assemble-seq.sh
- Goal
  Automate the process of trimming, reverse complementing and merging Sanger sequencing results
- Notes
  1. There is a program already written for this purpose [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5066597/][link]]
  2. I can't use it directly, so I opted to write my own
- Requirement
  1. Install EMBOSS
     #+BEGIN_SRC bash
     brew tap brewsci/bio
     brew install EMBOSS
     #+END_SRC
  2. Install bioawk (used to parse fasta files)
     #+BEGIN_SRC bash
     git clone git://github.com/lh3/bioawk.git 
     cd bioawk 
     make 
     cp bioawk ~/bin/
     #+END_SRC
- Script :: assemble-seq.sh
  a. extract all sequence names into a text file =strain_names.txt= using grep
  b. for each sequence name, use bioawk to extract the forward (p355) and the reverse (p400, p077 or p032) sequences
     + if the strain has been sequenced with p400, first merge p355 with p400 and output that as the new fwd.fa
     + for all strains, take the fwd.fa (either the p355 or the p355-p400 merged) and merge it with rev.fa (p077 or p032)
  c. concatenate all merged sequences to =../output/2018-10-07-assembled-seq.fa=
