---
title: "Chimeric Pho4 data analyzer v2"
author: "Bin He"
date: '2022-06-20 updated `r Sys.Date()`'
output:
  html_notebook:
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
suppressPackageStartupMessages(require(shinyWidgets))
suppressPackageStartupMessages(require(DT))
suppressPackageStartupMessages(require(plotly))
suppressPackageStartupMessages(require(tidyverse))
suppressPackageStartupMessages(require(cowplot))
suppressPackageStartupMessages(require(ggtext))
```

Flow cytometry data is generated by Emily O'Brien with help from Lindsey Snyder. Data was collected in 2022.03-06.

For QC plots, see [here](https://rpubs.com/emptyhb/e013-flow-analysis-060722).

```{r prepare_data, echo=FALSE}
# load data
load("20220620-data-for-interactive-plotting.RData")
# extract ximera names
ximeras <- sort(meta$symbol)
# for two groups, e.g., with vs w/o Pho2
cols.two <- c("PHO2" = "#457dbc", "pho2∆" = "#ea9e25")
# define groups for better visualization
ximera.grp <- datsum %>% 
  mutate(group = case_when(
    full < 0.2 ~ "defective",
    base > 5   ~ "less Pho2-dep.",
    TRUE       ~ "others"
  )) %>% select(plasmid, symbol, group)
```

## Selecting and plotting Pho4 chimera results {.tabset}
### Plot
<span style="color: red;">**Grouping**</span>  **defective** = activity with Pho2 less than 20% of ScPho4 with Pho2; **less Pho2-dep.** = activity w/o Pho2 > 5 times ScPho4 w/o Pho2
```{r eruptions, echo=FALSE}
fluidPage(

  # App title ----

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(
      div(
        # Input: Select the random distribution type ----
        awesomeCheckboxGroup(
          inputId = "ximera",
          label = "Pho4 chimera",
          choices = ximeras,
          selected = c("CCCCC", "SSSSS"),
          status = "success",
          inline = TRUE
        ),
        style = "font-family: monospace;"
      ),
      width = 2

      # Input: Slider for the number of observations to generate ----
    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Tabset w/ plot, summary, and table ----
      renderPlot({
        datT <- meta %>% 
          filter(symbol %in% input$ximera) %>% 
          inner_join(datO, by = "plasmid") %>% 
          mutate(symbol = factor(symbol, levels = input$ximera))
        
        p1 <- datT %>% 
          left_join(ximera.grp, by = c("symbol", "plasmid")) %>% 
          pivot_longer(c(nGFP, nRFP, RvG), names_to = "parameter", values_to = "intensity") %>% 
          mutate(parameter = ordered(parameter, levels = c("nGFP", "nRFP", "RvG"),
                                     labels = c("Pho4-GFP", "PHO5pr-RFP", "RFP/GFP"))) %>% 
          #pivot_longer(BL1.H:YL2.H, names_to = "parameter", values_to = "intensity") %>% 
          #mutate(parameter = ordered(parameter, levels = c("YL2.H", "BL1.H"))) %>% 
          ggplot(aes(x = symbol, y = intensity, group = host)) + 
          geom_bar(aes(fill = host), width = 0.5,# alpha = 0.8,
                   stat = "summary", fun = "mean", position = position_dodge(0.5)) +
          geom_point(aes(color = host), size = 1, alpha = 0.9, shape = 3,
                     position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.5)) + 
          scale_color_manual("co-TF", values = c("PHO2" = "gray30", "pho2∆" = "gray40")) +
          scale_fill_manual("co-TF", values = cols.two) +
          #stat_summary(fun = "mean", geom = "crossbar", color = "red", width = 0.25,
          #             position = position_dodge(0.75), ) +
          facet_grid(parameter~group, scale = "free", space = "free_x") +
          xlab("Pho4 chimera") + expand_limits(y = 0) +
          theme_bw(base_size = 18) + background_grid(minor = "none") +
          theme(axis.text.x = element_text(angle = 30, hjust = 1, family = "mono"),
                legend.position = "top", axis.title.x = element_blank(),
                strip.text = element_markdown(), plot.title = element_text(hjust = 0.5))

        p2 <- datT %>% 
          left_join(ximera.grp, by = c("symbol", "plasmid")) %>% 
          ggplot(aes(x = symbol, y = sRvG, group = host)) + 
          geom_bar(aes(fill = host), width = 0.5,# alpha = 0.8,
                   stat = "summary", fun = "mean", position = position_dodge(0.5)) +
          geom_point(aes(color = host), size = 1, alpha = 0.9, shape = 3,
                     position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.5)) + 
          geom_hline(yintercept = 1, linetype = 2, color = "gray30") +
          scale_color_manual(values = c("PHO2" = "gray30", "pho2∆" = "gray40"), guide = "none") +
          scale_fill_manual(values = cols.two, guide = "none") +
          facet_grid(host~group, scale = "free", space = "free_x") + ggtitle("Relative activities") +
          xlab("Pho4 chimera") + ylab("A<sub>chimera</sub> / A<sub>ScPho4</sub>") +
          theme_bw(base_size = 18) + background_grid(minor = "none") +
          theme(axis.text.x = element_text(angle = 30, hjust = 1, family = "mono"),
                strip.text = element_markdown(), 
                axis.title.x = element_blank(), axis.title.y = element_markdown(),
                plot.title = element_text(hjust = 0.5))
          
        p3 <- datsum %>% 
          filter(symbol %in% input$ximera) %>% 
          left_join(ximera.grp, by = c("plasmid", "symbol")) %>% 
          ggplot(aes(x = symbol, y = boost)) +  
          geom_col(width = 0.3, color = "black", fill = "gray80") + 
          geom_hline(yintercept = 1, linetype = 2, color = "gray30") +
          facet_grid(.~group, scales = "free_x", space = "free_x") + 
          scale_y_log10() +
          xlab("Pho4 chimera") + ggtitle("A<sub>PHO2</sub> / A<sub>pho2∆</sub>") +
          theme_bw(base_size = 18) + background_grid(minor = "none") +
          theme(axis.text.x = element_text(angle = 30, hjust = 1, family = "mono"),
                strip.text = element_blank(), plot.title = element_markdown(hjust = 0.5))
        
        set_null_device("png") 
        plot_grid(p1, p2, p3, ncol = 1, rel_heights = c(6,4,3))
      }, height = 900),
      
      renderText({
        "**Note** In the middle pane, the PHO2 value represents the ratio between A_PHO2 for the chimera against that of ScPho4 from the same plate. So is the pho2∆ values. This achieves two goals: compare the activities against ScPho4 and remove some of the run-to-run variation"
      }),
      width = 10 
    )
  )
)
```

### Chimera summary & lookup
```{r}
renderDT(datsum %>% relocate(symbol, .after = plasmid) %>% select(-letter), rownames = FALSE)
```

### Summary plot
```{r}
p4 <- datsum %>% 
  mutate(Pho4 = ifelse(symbol == "SSSSS", "ScPho4", ifelse(symbol == "CCCCC", "CgPho4", "Chimera")),
         Pho4 = factor(Pho4, levels = c("ScPho4", "CgPho4", "Chimera"))) %>% 
  ggplot(aes(x = `A_PHO2`, y = `A_pho2`, label = symbol, color = Pho4)) + 
  geom_point(size = 2.5) + geom_abline(slope = 1) +
  scale_color_manual(values = c("ScPho4" = "blue3", "CgPho4" = "forestgreen", Chimera = "black")) +
  scale_x_continuous(limits = c(NA, 60), oob = scales::oob_squish) +
  theme_gray(base_size = 14)
ggplotly(p4, tooltip = c("label", "x", "y"), width = 900)
```

