---
title: "Chimeric Pho4 data analyzer"
author: "Bin He"
date: '2022-04-12 updated `r Sys.Date()`'
output:
  html_notebook:
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
suppressPackageStartupMessages(require(shinyWidgets))
suppressPackageStartupMessages(require(plotly))
suppressPackageStartupMessages(require(tidyverse))
suppressPackageStartupMessages(require(cowplot))
```

Flow cytometry data is generated by Emily O'Brien with help from Lindsey Snyder. Data was collected in 2022.03-04.

For QC plots, see [here](https://rpubs.com/emptyhb/pho4-chimera-flow-040122).

Prepare data
```{r echo=FALSE}
# load data
dat1 <- read_tsv("20220412-bg-sub-data.tsv", col_types = "cccfddddd")
meta <- read_tsv("20220330-chimera-Pho4-makeup.tsv", col_types = "cccc")
# extract ximera names
ximeras <- sort(meta$symbol)
# create summarized data
datsum <- dat1 %>%
  filter(plasmid != "NA") %>% 
  mutate(`R/G` = YL2.H/BL1.H, `nR/G` = nRFP/nGFP) %>% 
  group_by(date, plasmid, host) %>% 
  summarize(across(c(YL2.H, nRFP, `R/G`, `nR/G`), mean), .groups = "drop") %>% 
  pivot_wider(names_from = host, values_from = YL2.H:`nR/G`) %>% 
  mutate(`pho2∆/PHO2` = `R/G_pho2∆`/`R/G_PHO2`,
         `n.pho2∆/PHO2` = `nR/G_pho2∆`/`nR/G_PHO2`)

# useful to set a flag for low activity mutants
low.act.th <- datsum %>% filter(plasmid == "194") %>% summarize(across(.cols = where(is.numeric), .fns = mean)) %>% unlist()
```

## Selecting and plotting Pho4 chimera results {.tabset}

### Plot
```{r eruptions, echo=FALSE}
fluidPage(

  # App title ----

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(
      div(
        # Input: Select the random distribution type ----
        awesomeCheckboxGroup(
          inputId = "ximera",
          label = "Pho4 chimera",
          choices = ximeras,
          selected = c("CCCCC", "SSSSS"),
          status = "success",
          inline = TRUE
        ),
        style = "font-family: monospace;"
      ),
      width = 2

      # Input: Slider for the number of observations to generate ----
    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Tabset w/ plot, summary, and table ----
      renderPlot({
        p1 <- meta %>% 
          filter(symbol %in% input$ximera) %>% 
          inner_join(dat1, by = "plasmid") %>% 
          mutate(symbol = factor(symbol, levels = input$ximera)) %>% 
          pivot_longer(nGFP:nRFP, names_to = "parameter", values_to = "intensity") %>% 
          mutate(parameter = ordered(parameter, levels = c("nRFP", "nGFP"))) %>% 
          #pivot_longer(BL1.H:YL2.H, names_to = "parameter", values_to = "intensity") %>% 
          #mutate(parameter = ordered(parameter, levels = c("YL2.H", "BL1.H"))) %>% 
          ggplot(aes(x = symbol, y = intensity, group = host)) + 
          geom_bar(aes(fill = host), width = 0.5, alpha = 0.8,
                   stat = "summary", fun = "mean", position = position_dodge(0.5)) +
          geom_point(aes(color = host), size = 1,
                     position = position_jitterdodge(dodge.width = 0.5)) + 
          scale_color_manual(values = c("PHO2" = "gray20", "pho2∆" = "gray40")) +
          scale_fill_viridis_d(begin = 0.2, end = 0.6) +
          #stat_summary(fun = "mean", geom = "crossbar", color = "red", width = 0.25,
          #             position = position_dodge(0.75), ) +
          facet_wrap(~parameter, scale = "free_y", ncol = 1) +
          ggtitle("Individual components") + xlab("Pho4 chimera") + expand_limits(y = 0) +
          theme_gray(base_size = 18) +
          theme(axis.text.x = element_text(angle = 30, hjust = 1, family = "mono"),
                axis.title.x = element_blank(),
                plot.title = element_text(hjust = 0.5))
        p2 <- meta %>% 
          filter(symbol %in% input$ximera) %>% 
          inner_join(dat1, by = "plasmid") %>% 
          mutate(symbol = factor(symbol, levels = input$ximera)) %>% 
          mutate(`R/G` = nRFP/nGFP) %>% 
          ggplot(aes(x = symbol, y = `R/G`, group = host)) + 
          geom_bar(aes(fill = host), width = 0.5, alpha = 0.8,
                   stat = "summary", fun = "mean", position = position_dodge(0.5)) +
          geom_point(aes(color = host), position = position_jitterdodge(dodge.width = 0.5)) + 
          scale_color_manual(values = c("PHO2" = "gray20", "pho2∆" = "gray40")) +
          scale_fill_viridis_d(begin = 0.2, end = 0.6) +
          #stat_summary(fun = "mean", color = "red", geom = "crossbar", width = 0.2,
          #             position = position_dodge(0.75), ) +
          xlab("Pho4 chimera") + ggtitle("RFP/GFP") +
          theme_gray(base_size = 18) +
          theme(axis.text.x = element_text(angle = 30, hjust = 1, family = "mono"),
                axis.title.x = element_blank(),
                plot.title = element_text(hjust = 0.5))
        p3 <- meta %>% 
          filter(symbol %in% input$ximera) %>% 
          inner_join(datsum, by = "plasmid") %>% 
          mutate(symbol = factor(symbol, levels = input$ximera)) %>% 
          mutate(Activity = ifelse(`R/G_PHO2` < 2*low.act.th["R/G_pho2∆"], "low", "pass")) %>% 
          ggplot(aes(x = symbol, y = `pho2∆/PHO2`)) + 
          geom_col(aes(group = date, color = Activity, fill = `R/G_PHO2`), width = 0.5, 
                   position = position_dodge(0.5)) +
          scale_fill_gradient2("Activity") +
          scale_color_manual(values = c("low" = "red3", "pass" = "gray50"), guide = FALSE) +
          #stat_summary(fun = "mean", color = "red", geom = "crossbar", width = 0.2,
          #             position = position_dodge(0.75), ) +
          #facet_grid(.~Activity, scales = "free_x", space = "free_x", labeller = "label_both") +
          theme_gray(base_size = 18) + xlab("Pho4 chimera") +
          theme(axis.text.x = element_text(angle = 30, hjust = 1, family = "mono"), 
                axis.title.x = element_blank())
        plot_grid(p1, p2, p3, ncol = 1, rel_heights = c(3,2,1.5), align = "hv")
      }, height = 800),
      
      renderText({
        "Activity: R/G with Pho2. Any chimera whose activity with Pho2 is lower than 2*R/G in pho2∆ for ScPho4 (SSSSS) is arbitrarily labeled with a red outline as a warning."
      }),
      width = 10 
    )
  )
)
```

### Chimera lookup
```{r}
renderTable(meta)
```

### Summary plot
```{r}
p3 <- meta %>% 
  inner_join(datsum, by = "plasmid") %>% 
  mutate(Pho4 = ifelse(symbol == "SSSSS", "ScPho4", ifelse(symbol == "CCCCC", "CgPho4", "Chimera")),
         Pho4 = factor(Pho4, levels = c("ScPho4", "CgPho4", "Chimera")),
         `nR/G_PHO2` = round(`nR/G_PHO2`, digits = 2),
         `nR/G_pho2∆` = round(`nR/G_pho2∆`, digits = 2)) %>% 
  ggplot(aes(x = `nR/G_PHO2`, y = `nR/G_pho2∆`, label = symbol, color = Pho4)) + 
  geom_point(size = 2.5) + geom_abline(slope = 1) +
  scale_color_manual(values = c("ScPho4" = "blue3", "CgPho4" = "forestgreen", Chimera = "black")) +
  scale_x_continuous(limits = c(NA, 60), oob = scales::oob_squish) +
  theme_gray(base_size = 14)
ggplotly(p3, tooltip = c("label", "x", "y"), width = 900)
```
```

