#+title: notes on sequencing validation results
#+author: Bin He

* [2019-02-17 Sun] Carl, chimeric construct
/Did/
- Carl performed colony PCR with his Yeast transformation using a linear template derived from EB2129. He identified four colonies that show the expected size, purified the PCR product and sent it for sequencing.

/Result/
- The results, however, are very puzzling. He saw four different sequences, none of which match what he expects.
- I modified the [[file:~/Documents/work/current/E013-Pho4-evolution/01-validate-chimera/script/assemble-seq-2019-02-16.sh][assembe-seq.sh]] script and used it to assemble the four colony PCR products( [[file:~/Documents/work/current/E013-Pho4-evolution/01-validate-chimera/data/sequencing/2019-02-16-Carl-EB2129-colony-pcr-screen.fa][Sanger individual sequences]]). It turns out that c1,2,4 were sequenced through, while c6 was not.
  (to recreate the graphics, simply use BLAST two sequences and input the [[file:2019-02-16-Carl-EB2129-assembled.fa][assembled sequence]] and the [[file:~/Documents/work/current/E013-Pho4-evolution/01-validate-chimera/data/sequencing/2018-08-23-Pho4-CDS-EGFP.fa][ScPho4, CgPho4, YFP templates]]
  - c1 is purely CgPho4
  - c2 has a bit of CgPho4 in the N terminal and is otherwise ScPho4
  - c4, see E013 repo notes
  - c6 has yEGFP in the end, even though we used p400, which is supposed to anneal to the beginning of YFP in the reverse direction, with the intention of sequencing the C terminal of the chimera. Notably, the sequence match to YFP contains a large number of C->T mutations.
  - These results suggest to me that the PCR products used to transform the cells are problematic.

/Plan/
- The next step is to troubleshoot the PCR, potentially sequencing a few of the PCR products to make sure that they are what we expect them to be.
- After that we need to sequence the PCR products used for transformation, to make sure that there is only one species of molecules in it.
