---
title: "Ex009.3 Batch2n3 Estimate PCR cycle"
author: "Bin He"
date: "September 22, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

This script analyzes the qPCR result for the purpose of estimating the number of PCR cycles to run during the last step of RNAseq library prep.

## Input

qPCR output in long format

## Analysis

```{r load libraries}
require(reshape2)
require(ggplot2)
require(plyr)
```

```{r load data and preprocess}
raw <- read.table("../data/20170922_Ex009-3_batch23_estimate_PCR_cycle.csv", sep = "\t", as.is = TRUE, header = TRUE)
colnames(raw)[3] <- "dRn"
## remove unused wells
blank <- c(paste(LETTERS[1:8],"1",sep=""))
dat <- subset(raw, !is.na(dRn) & !(Well %in% blank))
```

```{r determine_50pct_threshold}
## idea: transform the dRn series to the empirical first order derivative by calculating the difference between the two consecutive cycles
first.driv <- ddply( dat, .(Well), function(X) {
  delta.dRn <- X$dRn[2:30] - X$dRn[1:29]
  res <- data.frame(Cycle = 2:30, delta.dRn)
  return(res)
})
## plot the first derivative
p <- ggplot( data = first.driv, aes( x = Cycle, y = delta.dRn, color = Well ) ) + geom_line() + geom_point( size = 0.5 )
print( p )

## now locate the cycle number that has the greatest first.driv for each well. Use that cycle # + 3 as the saturation value and normalize the results
norm.res <- ddply( dat, .(Well), function(X) {
  delta.dRn <- X$dRn[2:40] - X$dRn[1:39]
  max <- which.max(delta.dRn)
  sat <- X$dRn[max+3]
  res <- data.frame(Cycle = 1:39, n.dRn = X$dRn[1:39] / sat)
  return(res)
})
p1 <- ggplot( data = norm.res, aes( x = Cycle, y = n.dRn*100, color = Well ) ) + geom_line() + geom_point( size = 0.5 )

## finally, identify the cycle number that is closest to 50%
half.point <- ddply( norm.res, .(Well), function(X) {
  diff <- abs( X$n.dRn - 0.5 )
  half <- which.min( diff )
  return(c(Cycle = half, n.dRn = X$n.dRn[half]))
})
print(p1 + geom_point( data = half.point, aes( x = Cycle, y = n.dRn*100, color = Well ), size = 3, shape = 1 ) + xlim(c(5,25)))
cycle.50pct <- matrix(half.point$Cycle, byrow = TRUE, ncol = 4)
dimnames(cycle.50pct) <- list(LETTERS[1:8],2:5)
print("RESULTS")
print(cycle.50pct)
```
