---
title: "Deep well shaken uniformity"
output: html_notebook
---

```{r}
require(tidyverse)
require(cowplot)
```

## Goal

- Test the uniformity of reporter levels in a deep well plate with shaking and 3 mm glass beads
- Test the new plate design

## Data

Processed with the R script in this folder, exported as a CSV file.

```{r}
dat <- read_tsv("20220104-gated-median-out.txt") %>% 
  # remove the tube samples
  filter(!grepl("A2-",name), sample != "neg") %>% 
  mutate(col = factor(col, levels = 1:12))
meta <- tibble(
  sample = c("B18", "yH156", "yH296", "yH295", "yH372", "yH373"),
  PHO4 = c("ScPho4", rep("pho4∆", 5)),
  PHO2 = c("PHO2", "pho2∆", "PHO2", "pho2∆", "PHO2", "pho2∆"),
  PHO5pr.RFP = c("ura3", "neg", "ura3", "ura3", "pho5", "pho5")
)
```

## Analysis
### Uniformity

Define the plot components
```{r}
pShare <- list(
  scale_y_discrete(limits = rev),
  theme_minimal(),
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank())
)
pFSC <- list(
  geom_tile(aes(fill = FSC.H)),
  geom_text(aes(label = round(FSC.H/1000,0))),
  scale_fill_fermenter(palette = "Greys", direction = 1),
  theme_cowplot()
)
pGFP <- list(
  geom_tile(aes(fill = BL1.H)),
  geom_text(aes(label =  round(BL1.H/100,0))),
  scale_fill_fermenter(palette = "Greens", direction = 1)
)
pRFP <- list(
  geom_tile(aes(fill = YL2.H)),
  geom_text(aes(label =  round(YL2.H/1000,0))),
  scale_fill_fermenter(palette = "Reds", direction = 1)
)
pnGFP <- list(
  geom_tile(aes(fill = nGFP)),
  geom_text(aes(label =  round(nGFP/100,0))),
  scale_fill_fermenter(palette = "Greens", direction = 1)
)
pnRFP <- list(
  geom_tile(aes(fill = nRFP)),
  geom_text(aes(label =  round(nRFP/1000,0))),
  scale_fill_fermenter(palette = "Reds", direction = 1)
)
```

Plot FSC
```{r}
sp <- "B18"
# FSC
dat %>%
  filter(sample == sp) %>% 
  ggplot(aes(x = col, y = row)) + pShare + pFSC + ggtitle("01/04 FSC.H")
```

Plot the mNeon and mCherry data across the plate
```{r}
# GFP
p1 <- dat %>%
  filter(sample == sp) %>% 
  ggplot(aes(x = col, y = row)) + pShare+ pGFP + ggtitle("BL1.H")
# RFP
p2 <- dat %>%
  filter(sample == sp) %>% 
  ggplot(aes(x = col, y = row)) + pShare+ pRFP + ggtitle("YL2.H")
# normalized GFP
p3 <- dat %>%
  filter(sample == sp) %>% 
  ggplot(aes(x = col, y = row)) + pShare+ pnGFP + ggtitle("nGFP")
# normalized RFP
p4 <- dat %>%
  filter(sample == sp) %>% 
  ggplot(aes(x = col, y = row)) + pShare+ pnRFP + ggtitle("nRFP")
plot_grid(p1, p2, p3, p4, ncol = 2)
```

